##  Data set
mode: 'Unseen_patient' # mode option: 'Same_patient' & 'Unseen_patient'
task: 'Move_Rest' # Task options: 'Singing_Music' & 'Move_Rest'
load_preprocessed_data: True
num_patient: 12 # Number of patients (Music Reconstruction: 29, Upper-Limb Movement: 12)

##  Model Settings:
hyper_param:
  F1: 12
  dropoutRate: 0.647
  kernLength: 40
  kernLength_sep: 10
  dropoutType: 'SpatialDropout2D'
  D: 2


n_ROI: 15 # Number of Regions of Interest
coef_reg: 0.01 # Regularization coefficient


## Evaluation
n_folds: 12  # number of folds (Use one patient out cross-validation, set n_folds to 1)
inner_fold: 3
# Type of data balancing ('move_rest': 'no_balancing', 'Singing_Music': 'over_sampling')
type_balancing: 'no_balancing'
debug_mode: false # if it's true it saves the results in debug folder inside results

## Training options
epochs: 300 # Number of training epochs
patience: 20 # Patience for early stopping
early_stop_monitor: 'val_accuracy' # Metric to monitor for early stopping
optimizer: 'adam' # Optimizer to use
loss: 'categorical_crossentropy' # Loss function
del_temporal_lobe: False


